### ISSUE TITLE
Better naming?

### ISSUE THREAD

**Issue by samdark** [yiisoft/access#1]
TODO:

- [ ] `checkAccess()` -> `hasAccess()`

---

Current it is `CheckAccessInterface` and `checkAccess()`.

I propose renaming to `AccessChecker` and `hasAccess()`.

**Comment by fcaldarelli** [comment]
I'd follow one of two already used convention:

- "Interface" suffix (as now);
- "-able" , "-ible" suffix;

So, it could be called CheckableAccess and method "hasAccess" as you wrote.

**Comment by samdark** [comment]
@machour, @SilverFire, @hiqsol?

**Comment by hiqsol** [comment]
I would follow PSR approach with `-erInterface` postfix.
So: `AccessCheckerInterface` and `checkAccess()`

**Comment by SilverFire** [comment]
1. I would not stick method names to the interface name, but rather to possible implementation class name. It's a common thing to have something like `User implemets CheckAccessInterface`. Then it makes sense to name method `hasAccess()` so `$user->hasAccess()`

2. For me `checkAccess()` looks similar to `ensure` naming convention, when an exception is thrown when something is not OK. Meanwhile `is` and `has` are expected to return boolean

**Comment by machour** [comment]
+1 on @SilverFire proposal

**Comment by machour** [comment]
I think the repository/package name should be revised too. contract-access?

**Comment by viktorprogger** [comment]
+1 @hiqsol proposal because
- it's PSR
- it suites my own preferences

**Comment by hiqsol** [comment]
In the current implementation `User` is not about to implement CheckAccessInterface.
It is `AuthManager` who implements the interface.

The principal question is what arguments the method takes.
The current implementation:

```php
function checkAccess($usedId, $permissionName, $params = []);
```

I mean we will not pass userId into `User::hasAccess()`.

Do we want the interface for `AuthManager` or for `User`?

**Comment by hiqsol** [comment]
Otherwise good point about `check` vs `has`.

**Comment by samdark** [comment]
This interface is for auth manager.

**Comment by hiqsol** [comment]
How about `AuthManagerInterface` then?
It will protect from confusing to use it in User.

**Comment by samdark** [comment]
It's not for managing auth. It's for checking for permissions only so that would be super-confusing about its purpose.

**Comment by terabytesoftw** [comment]
If it is only to verify the permissions of the users, the proposal of @SilverFire +1

**Comment by samdark** [comment]
How about `CheckAccessInterface` → `PermissionChecker`?
